version: '3.8'

networks:
    app-network:
      driver: bridge

services:
  web:
    build: ./web
    container_name: web
    restart: unless-stopped
    command: npm run dev
    ports:
      - "9000:9000"
    volumes:
      - ./web:/usr/app
      - /usr/app/node_modules
    networks:
      - app-network
  
  php:
    image: crmsolucoes/php-fpm-8.2:latest
    container_name: php
    restart: unless-stopped
    volumes:
      - ./server:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine 
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./server:/var/www/html
      - ./server/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sqlserver
      - php
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlsrv
    user: root
    restart: unless-stopped
    environment:
      SA_PASSWORD: Pass@word
      MSSQL_PID: Developer
      ACCEPT_EULA: "Y"
    volumes:
      - ./db:/var/opt/mssql/data
    ports:
      - 1433:1433
    networks:
      - app-network

