version: '3.8'

networks:
    app-network:
      driver: bridge

services:
  web:
    build: ./web
    container_name: web
    restart: unless-stopped
    command: npm run dev
    ports:
      - "9000:9000"
    volumes:
      - ./web:/usr/app
    networks:
      - app-network

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /usr/server
    volumes:
      - ./server:/var/www
    networks:
      - app-network
  
  php:
    build: ./server
    container_name: php
    restart: unless-stopped
    volumes:
      - ./server:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine 
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./server:/var/www/html
      - ./server/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlsrv
    user: root
    container_name: sqlsrv
    restart: unless-stopped
    environment:
      SA_PASSWORD: Pass@word
      MSSQL_PID: Developer
      ACCEPT_EULA: "Y"
    volumes:
      - ./db:/var/opt/mssql/data
    ports:
      - 1433:1433
    networks:
      - app-network

